### ISSUE TITLE
Error when runing XOR

### ISSUE THREAD

**Issue by zxzhijia** [syntapy/brian_xor#2]
I downloaded your codes and tried to run xor.py on spyder installed with brian 2. it gave me the error below.

'import sitecustomize' failed; use -v for traceback
Traceback (most recent call last):
  File "/home/xuzhang/下载/brian_xor-brian2_lists_net/xor.py", line 4, in <module>
    import brian2 as br
  File "/home/xuzhang/anaconda2/lib/python2.7/site-packages/brian2/**init**.py", line 51, in <module>
    from pylab import *
  File "/home/xuzhang/anaconda2/lib/python2.7/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/home/xuzhang/anaconda2/lib/python2.7/site-packages/matplotlib/pylab.py", line 231, in <module>
    import matplotlib.finance
  File "/home/xuzhang/anaconda2/lib/python2.7/site-packages/matplotlib/finance.py", line 25, in <module>
    from matplotlib.dates import date2num
  File "/home/xuzhang/anaconda2/lib/python2.7/site-packages/matplotlib/dates.py", line 136, in <module>
    import matplotlib.cbook as cbook
AttributeError: 'module' object has no attribute 'cbook'

**Comment by syntapy** [comment]
Hi! Maybe you don't have the proper packages installed?

Anyhow, I'd suggest you use this code instead: https://github.com/syntapy/normad
Check the v0.1 tag. It should run and solve XoR problem right off the bat

I've also included the requirements.txt file. If you're familiar with python virtual environment tools such as virtualenvwrapper and anaconda, you can use this to install the packages / versions I've been using to develope this code and it should run straightaway. Let me know if you have any questions!

That code is more recent than the brian_xor. Honestly, the brian_xor code is quite horrible! I should probably delete this repo honestly

**Comment by zxzhijia** [comment]
Thank you. I'll try that.
